### DISCUSSION TITLE
Agregar espacio antes del Punto

### DISCUSSION THREAD

**Discussion by MardoDan** [ajtruckle/meeting-schedule-assistant-support#38] [Q&A] [answered]
¿Cómo podemos agregar más espacio entre el Punto de Palabras de Introducción y Palabras de Conclusión?

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/122133558/343c8ae4-1ab6-45ba-a824-8f8331e6f186)

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/122133558/279c795b-ee2f-4e65-8171-2ab9b3dd9795)

Muchas gracias.

**Comment by ajtruckle** [comment, marked as answer]
@MardoDan 

> How can we add more space between the Intro Word Point and Conclusion Word Point?

If you use the **Inspect** feature in the _Meeting Editor_ you will be able to find out which HTML classes the bullet points are using:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/27d2f98c-026e-4a24-b9de-4ee3020cb152)

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/34fba4a8-38c1-4a5d-9690-f5acd43f47fd)

[Inspect](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/css/inspect) indicates that the following _classes_ control how the bullets are displayed:

```css
.bulletTFGW {
    padding-right: 1mm;
    color: #606a70;
    font-weight: normal;
}

.bulletLAC {
    padding-right: 1mm;
    color: #961526;
    font-weight: normal;
}
```
Both _classes_ set the [`padding-right`](https://www.w3schools.com/cssref/pr_padding-right.php) property to `1mm`. Increase this value to add more space.  Does this answer your question?
