### ISSUE TITLE
Problem with ‘1 slip for page’ setting

### ISSUE THREAD

**Issue by stecchio66** [ajtruckle/meeting-schedule-assistant-support#139]
@ajtruckle 
Maybe there is a bug: Even if i select the “one for page” setting, 4 are printed.
You can check?

Thanks!

**Comment by ajtruckle** [comment]
@stecchio66 
Apologies for the inconvenience this issue has caused. Please follow these steps to locate and edit the file:"

1. Open the Slips view, right-click, and select "Open file location" from the context menu.
2. Navigate to the 11-2023 sub-folder and double-click to open it.
3. Find the s-89-ita.css file and open it with a text editor.

Change:

```css
.containerSlip {
	float:left;
	position: relative;
	margin: 3mm;
}
```

to:

```css
.containerSlip {
	position: relative;
	margin: 3mm;
}
```

And also add this to the end of the file:

```css
@media screen {
	.containerSlip {
	float:left;
	}
}
```

These changes should resolve the issue. The updated file should now appear as follows:

```css
body {
	font-family: 'Arial Unicode MS';
	font-size: 10pt;
}

.containerPage {}

.containerSlip {
	position: relative;
	margin: 3mm;
}

.fieldName {
	position: absolute;
	left: 160px;
	top: 60px;
	width: 150px;
}

.fieldAssisant {
	position: absolute;
	left: 105px;
	top: 91px;
	width: 205px;
}

.fieldDate {
	position: absolute;
	left: 62px;
	top: 122px;
	width: 245px;
}

.fieldPartNo {
	position: absolute;
	left: 85px;
	top: 153px;
	width: 225px;
}

.fieldCounsel {
	position: absolute;
	left: 15px;
	top: 180px;
	width: 295px;
	background-color: yellow;
}

.checkMainHall {
	position: absolute;
	left: 37px;
	top: 223px;
	width: 15px;
}

.checkAuxClass1 {
	position: absolute;
	left: 37px;
	top: 243px;
	width: 15px;
}

.checkAuxClass2 {
	position: absolute;
	left: 37px;
	top: 262px;
	width: 15px;
}

@media screen {
	.containerSlip {
	float:left;
	}
}
```

Please give it a try and let me know how it goes. If everything works as expected, I'll proceed with updating the S-89 template files.
